Sprint 3
KozlovAleksandr/middle.messenger.praktikum.yandex pull request #4
Opened 2023-01-27 23:48 UTC by KozlovAleksandr

2023-01-29 13:07 UTC, podlovchenko requested changes
Привет, спасибо за проделанную работу, есть некоторые замечания:
1. Нет редиректа, если пользователь уже авторизован
2. Есть ошибки типизации, попробуй выполнить команду `npx tsc --noEmit`
3. При обновлении страницы на нетлифай page not found,  при обновлении локально cannot GET /sign-up
Жду правок)

2023-01-29 13:07 UTC, podlovchenko commented on package.json
>    },
Было бы отлично добавить команды для запуска линтеров и проверки типизации

2023-01-29 13:07 UTC, podlovchenko commented on src/api/UserApi.ts
> +  user(id: number) {
Названия методов лучше называть так, чтобы было понятно что они делают
В данном случае можно назвать getUser, так будет понятно, что этот метод возвращает информацию о пользователе, а не например создает его

2023-01-29 13:07 UTC, podlovchenko commented on src/components/buttonChatList/index.ts
> +export { ButtonChatList as default } from "./buttonChatList";
Использование дефолтных экспортов, на мой взгляд, это не очень хорошая практика.

Они позволяют задавать разные имена импортируемым объектам, из-за этого страдает читабельность, экземпляры с разными именами очень трудно потом искать по проекту. Так же затрудняется рефакторинг таких импортов.

Если задавать обычный экспорт, мы можем быть почти везде точно уверены, что имена используются везде одинаковые и IDE в таком случае спокойно их сможет поменять в случае рефакторинга.

Хорошая статья на эту тему
https://humanwhocodes.com/blog/2019/01/stop-using-default-exports-javascript-module/

2023-01-29 13:07 UTC, podlovchenko commented on src/components/controlledInput/controlledInput.ts
>          //   {type: VatidateRuleType.Password, value: inputEl.value},
Не стоит оставлять комментарии в коде, ухудшают читабельность

2023-01-29 13:07 UTC, podlovchenko commented on src/components/controlledInput/controlledInput.ts
> -          ]);
В данном кейсе подойдет конструкция switch case

2023-01-29 13:07 UTC, podlovchenko commented on src/components/inputBox/inputBox.scss
> +    button {
Лучше использовать классы, а не теги
Статья на эту тему https://frontstuff.io/you-need-to-stop-targeting-tags-in-css

2023-01-29 13:07 UTC, podlovchenko commented on src/core/Block.ts
> +  _checkInDom() {
Не хватает модификатора private для приватных методов

2023-01-29 13:07 UTC, podlovchenko commented on src/store/index.ts
> +
В проекте в некоторых файлах есть ошибка EOF
Для git важно наличие пустой строки в конце файла
https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log

2023-01-29 13:07 UTC, podlovchenko commented on typings/app.d.ts
> +    is_read: boolean;
Лучше называть поля в одном формате camelCase или snake_case

2023-01-29 22:04 UTC, KozlovAleksandr commented on src/store/index.ts
> +
Странно , в vscode стоит настройка "insert final newline". Должна же ставить новую строку. Пробежался по файлам , вроде не увидел , чтобы где то отсутствовала.

2023-01-29 22:05 UTC, KozlovAleksandr commented on typings/app.d.ts
> +    is_read: boolean;
Тут поменял. Дальше побоялся в спешке искать и менять , чтобы ничего не накрылось ) Но на будущее обязательно учту

2023-01-29 22:13 UTC, KozlovAleksandr commented on src/core/Block.ts
> +  _checkInDom() {
Дополнил

2023-01-29 22:17 UTC, KozlovAleksandr commented on src/components/inputBox/inputBox.scss
> +    button {
Тут поменял. В дальнейшем буду придерживаться этого правила.
P.S. очень доскональная проверка. Вау! Круто

2023-01-29 22:19 UTC, KozlovAleksandr commented on src/components/controlledInput/controlledInput.ts
> -          ]);
Тут позвольте пока так оставить. Мне вообще не нравится как проверка реализована , поэтому одной только заменой конструкции не отделаться

2023-01-29 22:23 UTC, KozlovAleksandr commented on src/components/controlledInput/controlledInput.ts
>          //   {type: VatidateRuleType.Password, value: inputEl.value},
Да , комментарии лишние , извиняюсь за неудобство, но это пока для себя оставляю. 
Тут , в частности , надо валидацию переделать. Напоминание такое , неудачное

2023-01-29 22:31 UTC, KozlovAleksandr commented on src/components/buttonChatList/index.ts
> +export { ButtonChatList as default } from "./buttonChatList";
Исправил

2023-01-29 22:37 UTC, KozlovAleksandr commented on src/api/UserApi.ts
> +  user(id: number) {
Исправил

2023-01-29 22:54 UTC, KozlovAleksandr commented on package.json
>    },
Добавил

2023-01-30 07:46 UTC, KozlovAleksandr commented
Нет редиректа, если пользователь уже авторизован
## редирект добавил
Есть ошибки типизации, попробуй выполнить команду npx tsc --noEmit
## с этим есть проблемы , что то исправил , но многое ешь нужно разбирать
При обновлении страницы на нетлифай page not found, при обновлении локально cannot GET /sign-up
## на Нетлифай починил , страницы переключаются , а вот локально проблему воспроизвести не удалось , ошибок никаких не было

2023-01-30 09:46 UTC, podlovchenko commented
Привет, локально проект не собирается
<img width="564" alt="Снимок экрана 2023-01-30 в 12 44 19" src="https://user-images.githubusercontent.com/22602747/215442720-70ba1efb-4dc0-497d-96f0-0352453dd8cc.png">
Локально воспроизводится, если запустить сервер на экспресс, необходимо добавить
```
app.get('*', function(req, res) {
  res.sendFile(path.join(__dirname, '/dist/index.html'));
});
```

2023-01-30 19:43 UTC, KozlovAleksandr commented
Сервер пофиксил. Действительно роуминг локально не работал.
Но почему у тебя не собирается вообще не понимаю. Вот мои скрины где всё корректно проходит

![Снимок экрана 2023-01-30 в 22 29 46](https://user-images.githubusercontent.com/90009560/215578026-22b5b353-c534-4b7a-a465-aa8ed67e8f1b.png)
![Снимок экрана 2023-01-30 в 22 31 34](https://user-images.githubusercontent.com/90009560/215578131-3dde179e-abb1-4ee6-9315-ac6755162354.png)

2023-01-31 10:41 UTC, podlovchenko commented
Привет, из-за кеша
Лучше добавить опцию --no-cache к команде build, чтобы избежать ошибок в дальнейшем
Работу принимаю
Хорошего дня)

2023-02-01 19:05 UTC, merged